SELECT 
    DATE,
    TYPEID,
    AVERAGE,
    ROUND(
        (AVG(AVERAGE) OVER (PARTITION BY TYPEID ORDER BY DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) 
         - AVG(AVERAGE) OVER (PARTITION BY TYPEID ORDER BY DATE ROWS BETWEEN 13 PRECEDING AND 7 PRECEDING)) 
        / NULLIF(AVG(AVERAGE) OVER (PARTITION BY TYPEID ORDER BY DATE ROWS BETWEEN 13 PRECEDING AND 7 PRECEDING), 0) * 100, 
        2
    ) AS WEEKLYCHG
FROM 
    {{ref('trf_jita_history')}}
