SELECT
    TYPEID,
    DATE,
    AVERAGE,
    AVG(AVERAGE) OVER (
        PARTITION BY TYPEID 
        ORDER BY DATE 
        RANGE BETWEEN INTERVAL '365 DAY' PRECEDING AND CURRENT ROW
    ) AS YEARLYAVG,
    (AVERAGE / AVG(AVERAGE) OVER (
        PARTITION BY TYPEID 
        ORDER BY DATE 
        RANGE BETWEEN INTERVAL '365 DAY' PRECEDING AND CURRENT ROW
    )) * 100 AS YEARLYINDEX
FROM 
    trf_jita_history